### ISSUE TITLE
Figures

### ISSUE THREAD

**Issue by microsud** [simonezuffa/Casein_Manuscript#2]
Hi Simone,
Great to see the efforts for reproducible research!
Just make sure the final figures created in the `Figures` folder are in line with the journal policy for copyright. If the journal has copyrights to it then it is not usually allowed to add those figures. 

Cheers,
Sudarshan

**Comment by simonezuffa** [comment]
Hi Sudarshan,
Thanks for the suggestion!
The journal is open access and under CC BY 4.0 so it should ok. 
I will double check with the editors tho.
Thanks,
Simone
